char *snprintf_expected_result[] = {
	"hej h",
	"hej ho",
	"hej hop",
	"hej hopp",
	"hej hopp",
	"hej 4",
	"hej 47",
	"hej 471",
	"hej 4711",
	"hej 4711",
	"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVXYZ1234567890()[]{}+-;,:.@$!\"#%&/\\=?'`^~|<>*_\a\b\f\n\r",
	"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVXYZ1234567890()[]{}+-;,:.@$!\"#%&/\\=?'`^~|<>*_\a\b\f\n\r\t",
	"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVXYZ1234567890()[]{}+-;,:.@$!\"#%&/\\=?'`^~|<>*_\a\b\f\n\r\t\v",
	"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVXYZ1234567890()[]{}+-;,:.@$!\"#%&/\\=?'`^~|<>*_\a\b\f\n\r\t\v",
	"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVXYZ1234567890()[]{}+-;,:.@$!\"#%&/\\=?'`^~|<>*_\a\b\f\n\r\t\v",
	"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVXYZ",
	"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVXYZ1234567890()[]{}+-;,:.@$!\"#%&/\\=?'`^~|<>*_\a\b\f\n\r\t\vabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVXYZ1234567890()[]{}+-;,:.@$!\"#%&/\\=?'`^~|<>*_\a\b\f\n\r\t\v",
	NULL};