#ifndef ASMJIT_X86_X86GLOBALS_H_INCLUDED
#define ASMJIT_X86_X86GLOBALS_H_INCLUDED
#include <asmjit/core/archtraits.h>
#include <asmjit/core/inst.h>
ASMJIT_BEGIN_SUB_NAMESPACE(x86)
enum class CondCode : uint8_t {
  kO             = 0x00u,
  kNO            = 0x01u,
  kC             = 0x02u,
  kB             = 0x02u,
  kNAE           = 0x02u,
  kNC            = 0x03u,
  kAE            = 0x03u,
  kNB            = 0x03u,
  kE             = 0x04u,
  kZ             = 0x04u,
  kNE            = 0x05u,
  kNZ            = 0x05u,
  kBE            = 0x06u,
  kNA            = 0x06u,
  kA             = 0x07u,
  kNBE           = 0x07u,
  kS             = 0x08u,
  kNS            = 0x09u,
  kP             = 0x0Au,
  kPE            = 0x0Au,
  kPO            = 0x0Bu,
  kNP            = 0x0Bu,
  kL             = 0x0Cu,
  kNGE           = 0x0Cu,
  kGE            = 0x0Du,
  kNL            = 0x0Du,
  kLE            = 0x0Eu,
  kNG            = 0x0Eu,
  kG             = 0x0Fu,
  kNLE           = 0x0Fu,
  kZero          = kZ,
  kNotZero       = kNZ,
  kEqual         = kE,
  kNotEqual      = kNE,
  kCarry         = kC,
  kNotCarry      = kNC,
  kSign          = kS,
  kNotSign       = kNS,
  kNegative      = kS,
  kPositive      = kNS,
  kOverflow      = kO,
  kNotOverflow   = kNO,
  kSignedLT      = kL,
  kSignedLE      = kLE,
  kSignedGT      = kG,
  kSignedGE      = kGE,
  kUnsignedLT    = kB,
  kUnsignedLE    = kBE,
  kUnsignedGT    = kA,
  kUnsignedGE    = kAE,
  kBTZero        = kNC,
  kBTNotZero     = kC,
  kParityEven    = kP,
  kParityOdd     = kPO,
  kMaxValue      = 0x0Fu
};
static constexpr CondCode _reverse_cond_table[] = {
  CondCode::kO,
  CondCode::kNO,
  CondCode::kA ,
  CondCode::kBE,
  CondCode::kE,
  CondCode::kNE,
  CondCode::kAE,
  CondCode::kB ,
  CondCode::kS,
  CondCode::kNS,
  CondCode::kPE,
  CondCode::kPO,
  CondCode::kG,
  CondCode::kLE,
  CondCode::kGE,
  CondCode::kL
};
static ASMJIT_INLINE_CONSTEXPR CondCode reverse_cond(CondCode cond) noexcept { return _reverse_cond_table[uint8_t(cond)]; }
static ASMJIT_INLINE_CONSTEXPR CondCode negate_cond(CondCode cond) noexcept { return CondCode(uint8_t(cond) ^ 1u); }
namespace Inst {
  enum Id : uint32_t {
    kIdNone = 0,
    kIdAaa,
    kIdAad,
    kIdAadd,
    kIdAam,
    kIdAand,
    kIdAas,
    kIdAdc,
    kIdAdcx,
    kIdAdd,
    kIdAddpd,
    kIdAddps,
    kIdAddsd,
    kIdAddss,
    kIdAddsubpd,
    kIdAddsubps,
    kIdAdox,
    kIdAesdec,
    kIdAesdeclast,
    kIdAesenc,
    kIdAesenclast,
    kIdAesimc,
    kIdAeskeygenassist,
    kIdAnd,
    kIdAndn,
    kIdAndnpd,
    kIdAndnps,
    kIdAndpd,
    kIdAndps,
    kIdAor,
    kIdArpl,
    kIdAxor,
    kIdBextr,
    kIdBlcfill,
    kIdBlci,
    kIdBlcic,
    kIdBlcmsk,
    kIdBlcs,
    kIdBlendpd,
    kIdBlendps,
    kIdBlendvpd,
    kIdBlendvps,
    kIdBlsfill,
    kIdBlsi,
    kIdBlsic,
    kIdBlsmsk,
    kIdBlsr,
    kIdBndcl,
    kIdBndcn,
    kIdBndcu,
    kIdBndldx,
    kIdBndmk,
    kIdBndmov,
    kIdBndstx,
    kIdBound,
    kIdBsf,
    kIdBsr,
    kIdBswap,
    kIdBt,
    kIdBtc,
    kIdBtr,
    kIdBts,
    kIdBzhi,
    kIdCall,
    kIdCbw,
    kIdCdq,
    kIdCdqe,
    kIdClac,
    kIdClc,
    kIdCld,
    kIdCldemote,
    kIdClflush,
    kIdClflushopt,
    kIdClgi,
    kIdCli,
    kIdClrssbsy,
    kIdClts,
    kIdClui,
    kIdClwb,
    kIdClzero,
    kIdCmc,
    kIdCmovb,
    kIdCmovbe,
    kIdCmovl,
    kIdCmovle,
    kIdCmovnb,
    kIdCmovnbe,
    kIdCmovnl,
    kIdCmovnle,
    kIdCmovno,
    kIdCmovnp,
    kIdCmovns,
    kIdCmovnz,
    kIdCmovo,
    kIdCmovp,
    kIdCmovs,
    kIdCmovz,
    kIdCmp,
    kIdCmpbexadd,
    kIdCmpbxadd,
    kIdCmplexadd,
    kIdCmplxadd,
    kIdCmpnbexadd,
    kIdCmpnbxadd,
    kIdCmpnlexadd,
    kIdCmpnlxadd,
    kIdCmpnoxadd,
    kIdCmpnpxadd,
    kIdCmpnsxadd,
    kIdCmpnzxadd,
    kIdCmpoxadd,
    kIdCmppd,
    kIdCmpps,
    kIdCmppxadd,
    kIdCmps,
    kIdCmpsd,
    kIdCmpss,
    kIdCmpsxadd,
    kIdCmpxchg,
    kIdCmpxchg16b,
    kIdCmpxchg8b,
    kIdCmpzxadd,
    kIdComisd,
    kIdComiss,
    kIdCpuid,
    kIdCqo,
    kIdCrc32,
    kIdCvtdq2pd,
    kIdCvtdq2ps,
    kIdCvtpd2dq,
    kIdCvtpd2pi,
    kIdCvtpd2ps,
    kIdCvtpi2pd,
    kIdCvtpi2ps,
    kIdCvtps2dq,
    kIdCvtps2pd,
    kIdCvtps2pi,
    kIdCvtsd2si,
    kIdCvtsd2ss,
    kIdCvtsi2sd,
    kIdCvtsi2ss,
    kIdCvtss2sd,
    kIdCvtss2si,
    kIdCvttpd2dq,
    kIdCvttpd2pi,
    kIdCvttps2dq,
    kIdCvttps2pi,
    kIdCvttsd2si,
    kIdCvttss2si,
    kIdCwd,
    kIdCwde,
    kIdDaa,
    kIdDas,
    kIdDec,
    kIdDiv,
    kIdDivpd,
    kIdDivps,
    kIdDivsd,
    kIdDivss,
    kIdDppd,
    kIdDpps,
    kIdEmms,
    kIdEndbr32,
    kIdEndbr64,
    kIdEnqcmd,
    kIdEnqcmds,
    kIdEnter,
    kIdExtractps,
    kIdExtrq,
    kIdF2xm1,
    kIdFabs,
    kIdFadd,
    kIdFaddp,
    kIdFbld,
    kIdFbstp,
    kIdFchs,
    kIdFclex,
    kIdFcmovb,
    kIdFcmovbe,
    kIdFcmove,
    kIdFcmovnb,
    kIdFcmovnbe,
    kIdFcmovne,
    kIdFcmovnu,
    kIdFcmovu,
    kIdFcom,
    kIdFcomi,
    kIdFcomip,
    kIdFcomp,
    kIdFcompp,
    kIdFcos,
    kIdFdecstp,
    kIdFdiv,
    kIdFdivp,
    kIdFdivr,
    kIdFdivrp,
    kIdFemms,
    kIdFfree,
    kIdFiadd,
    kIdFicom,
    kIdFicomp,
    kIdFidiv,
    kIdFidivr,
    kIdFild,
    kIdFimul,
    kIdFincstp,
    kIdFinit,
    kIdFist,
    kIdFistp,
    kIdFisttp,
    kIdFisub,
    kIdFisubr,
    kIdFld,
    kIdFld1,
    kIdFldcw,
    kIdFldenv,
    kIdFldl2e,
    kIdFldl2t,
    kIdFldlg2,
    kIdFldln2,
    kIdFldpi,
    kIdFldz,
    kIdFmul,
    kIdFmulp,
    kIdFnclex,
    kIdFninit,
    kIdFnop,
    kIdFnsave,
    kIdFnstcw,
    kIdFnstenv,
    kIdFnstsw,
    kIdFpatan,
    kIdFprem,
    kIdFprem1,
    kIdFptan,
    kIdFrndint,
    kIdFrstor,
    kIdFsave,
    kIdFscale,
    kIdFsin,
    kIdFsincos,
    kIdFsqrt,
    kIdFst,
    kIdFstcw,
    kIdFstenv,
    kIdFstp,
    kIdFstsw,
    kIdFsub,
    kIdFsubp,
    kIdFsubr,
    kIdFsubrp,
    kIdFtst,
    kIdFucom,
    kIdFucomi,
    kIdFucomip,
    kIdFucomp,
    kIdFucompp,
    kIdFwait,
    kIdFxam,
    kIdFxch,
    kIdFxrstor,
    kIdFxrstor64,
    kIdFxsave,
    kIdFxsave64,
    kIdFxtract,
    kIdFyl2x,
    kIdFyl2xp1,
    kIdGetsec,
    kIdGf2p8affineinvqb,
    kIdGf2p8affineqb,
    kIdGf2p8mulb,
    kIdHaddpd,
    kIdHaddps,
    kIdHlt,
    kIdHreset,
    kIdHsubpd,
    kIdHsubps,
    kIdIdiv,
    kIdImul,
    kIdIn,
    kIdInc,
    kIdIncsspd,
    kIdIncsspq,
    kIdIns,
    kIdInsertps,
    kIdInsertq,
    kIdInt,
    kIdInt3,
    kIdInto,
    kIdInvd,
    kIdInvept,
    kIdInvlpg,
    kIdInvlpga,
    kIdInvlpgb,
    kIdInvpcid,
    kIdInvvpid,
    kIdIret,
    kIdIretd,
    kIdIretq,
    kIdJb,
    kIdJbe,
    kIdJecxz,
    kIdJl,
    kIdJle,
    kIdJmp,
    kIdJnb,
    kIdJnbe,
    kIdJnl,
    kIdJnle,
    kIdJno,
    kIdJnp,
    kIdJns,
    kIdJnz,
    kIdJo,
    kIdJp,
    kIdJs,
    kIdJz,
    kIdKaddb,
    kIdKaddd,
    kIdKaddq,
    kIdKaddw,
    kIdKandb,
    kIdKandd,
    kIdKandnb,
    kIdKandnd,
    kIdKandnq,
    kIdKandnw,
    kIdKandq,
    kIdKandw,
    kIdKmovb,
    kIdKmovd,
    kIdKmovq,
    kIdKmovw,
    kIdKnotb,
    kIdKnotd,
    kIdKnotq,
    kIdKnotw,
    kIdKorb,
    kIdKord,
    kIdKorq,
    kIdKortestb,
    kIdKortestd,
    kIdKortestq,
    kIdKortestw,
    kIdKorw,
    kIdKshiftlb,
    kIdKshiftld,
    kIdKshiftlq,
    kIdKshiftlw,
    kIdKshiftrb,
    kIdKshiftrd,
    kIdKshiftrq,
    kIdKshiftrw,
    kIdKtestb,
    kIdKtestd,
    kIdKtestq,
    kIdKtestw,
    kIdKunpckbw,
    kIdKunpckdq,
    kIdKunpckwd,
    kIdKxnorb,
    kIdKxnord,
    kIdKxnorq,
    kIdKxnorw,
    kIdKxorb,
    kIdKxord,
    kIdKxorq,
    kIdKxorw,
    kIdLahf,
    kIdLar,
    kIdLcall,
    kIdLddqu,
    kIdLdmxcsr,
    kIdLds,
    kIdLdtilecfg,
    kIdLea,
    kIdLeave,
    kIdLes,
    kIdLfence,
    kIdLfs,
    kIdLgdt,
    kIdLgs,
    kIdLidt,
    kIdLjmp,
    kIdLldt,
    kIdLlwpcb,
    kIdLmsw,
    kIdLods,
    kIdLoop,
    kIdLoope,
    kIdLoopne,
    kIdLsl,
    kIdLss,
    kIdLtr,
    kIdLwpins,
    kIdLwpval,
    kIdLzcnt,
    kIdMaskmovdqu,
    kIdMaskmovq,
    kIdMaxpd,
    kIdMaxps,
    kIdMaxsd,
    kIdMaxss,
    kIdMcommit,
    kIdMfence,
    kIdMinpd,
    kIdMinps,
    kIdMinsd,
    kIdMinss,
    kIdMonitor,
    kIdMonitorx,
    kIdMov,
    kIdMovabs,
    kIdMovapd,
    kIdMovaps,
    kIdMovbe,
    kIdMovd,
    kIdMovddup,
    kIdMovdir64b,
    kIdMovdiri,
    kIdMovdq2q,
    kIdMovdqa,
    kIdMovdqu,
    kIdMovhlps,
    kIdMovhpd,
    kIdMovhps,
    kIdMovlhps,
    kIdMovlpd,
    kIdMovlps,
    kIdMovmskpd,
    kIdMovmskps,
    kIdMovntdq,
    kIdMovntdqa,
    kIdMovnti,
    kIdMovntpd,
    kIdMovntps,
    kIdMovntq,
    kIdMovntsd,
    kIdMovntss,
    kIdMovq,
    kIdMovq2dq,
    kIdMovs,
    kIdMovsd,
    kIdMovshdup,
    kIdMovsldup,
    kIdMovss,
    kIdMovsx,
    kIdMovsxd,
    kIdMovupd,
    kIdMovups,
    kIdMovzx,
    kIdMpsadbw,
    kIdMul,
    kIdMulpd,
    kIdMulps,
    kIdMulsd,
    kIdMulss,
    kIdMulx,
    kIdMwait,
    kIdMwaitx,
    kIdNeg,
    kIdNop,
    kIdNot,
    kIdOr,
    kIdOrpd,
    kIdOrps,
    kIdOut,
    kIdOuts,
    kIdPabsb,
    kIdPabsd,
    kIdPabsw,
    kIdPackssdw,
    kIdPacksswb,
    kIdPackusdw,
    kIdPackuswb,
    kIdPaddb,
    kIdPaddd,
    kIdPaddq,
    kIdPaddsb,
    kIdPaddsw,
    kIdPaddusb,
    kIdPaddusw,
    kIdPaddw,
    kIdPalignr,
    kIdPand,
    kIdPandn,
    kIdPause,
    kIdPavgb,
    kIdPavgusb,
    kIdPavgw,
    kIdPblendvb,
    kIdPblendw,
    kIdPclmulqdq,
    kIdPcmpeqb,
    kIdPcmpeqd,
    kIdPcmpeqq,
    kIdPcmpeqw,
    kIdPcmpestri,
    kIdPcmpestrm,
    kIdPcmpgtb,
    kIdPcmpgtd,
    kIdPcmpgtq,
    kIdPcmpgtw,
    kIdPcmpistri,
    kIdPcmpistrm,
    kIdPconfig,
    kIdPdep,
    kIdPext,
    kIdPextrb,
    kIdPextrd,
    kIdPextrq,
    kIdPextrw,
    kIdPf2id,
    kIdPf2iw,
    kIdPfacc,
    kIdPfadd,
    kIdPfcmpeq,
    kIdPfcmpge,
    kIdPfcmpgt,
    kIdPfmax,
    kIdPfmin,
    kIdPfmul,
    kIdPfnacc,
    kIdPfpnacc,
    kIdPfrcp,
    kIdPfrcpit1,
    kIdPfrcpit2,
    kIdPfrcpv,
    kIdPfrsqit1,
    kIdPfrsqrt,
    kIdPfrsqrtv,
    kIdPfsub,
    kIdPfsubr,
    kIdPhaddd,
    kIdPhaddsw,
    kIdPhaddw,
    kIdPhminposuw,
    kIdPhsubd,
    kIdPhsubsw,
    kIdPhsubw,
    kIdPi2fd,
    kIdPi2fw,
    kIdPinsrb,
    kIdPinsrd,
    kIdPinsrq,
    kIdPinsrw,
    kIdPmaddubsw,
    kIdPmaddwd,
    kIdPmaxsb,
    kIdPmaxsd,
    kIdPmaxsw,
    kIdPmaxub,
    kIdPmaxud,
    kIdPmaxuw,
    kIdPminsb,
    kIdPminsd,
    kIdPminsw,
    kIdPminub,
    kIdPminud,
    kIdPminuw,
    kIdPmovmskb,
    kIdPmovsxbd,
    kIdPmovsxbq,
    kIdPmovsxbw,
    kIdPmovsxdq,
    kIdPmovsxwd,
    kIdPmovsxwq,
    kIdPmovzxbd,
    kIdPmovzxbq,
    kIdPmovzxbw,
    kIdPmovzxdq,
    kIdPmovzxwd,
    kIdPmovzxwq,
    kIdPmuldq,
    kIdPmulhrsw,
    kIdPmulhrw,
    kIdPmulhuw,
    kIdPmulhw,
    kIdPmulld,
    kIdPmullw,
    kIdPmuludq,
    kIdPop,
    kIdPopa,
    kIdPopad,
    kIdPopcnt,
    kIdPopf,
    kIdPopfd,
    kIdPopfq,
    kIdPor,
    kIdPrefetch,
    kIdPrefetchit0,
    kIdPrefetchit1,
    kIdPrefetchnta,
    kIdPrefetcht0,
    kIdPrefetcht1,
    kIdPrefetcht2,
    kIdPrefetchw,
    kIdPrefetchwt1,
    kIdPsadbw,
    kIdPshufb,
    kIdPshufd,
    kIdPshufhw,
    kIdPshuflw,
    kIdPshufw,
    kIdPsignb,
    kIdPsignd,
    kIdPsignw,
    kIdPslld,
    kIdPslldq,
    kIdPsllq,
    kIdPsllw,
    kIdPsmash,
    kIdPsrad,
    kIdPsraw,
    kIdPsrld,
    kIdPsrldq,
    kIdPsrlq,
    kIdPsrlw,
    kIdPsubb,
    kIdPsubd,
    kIdPsubq,
    kIdPsubsb,
    kIdPsubsw,
    kIdPsubusb,
    kIdPsubusw,
    kIdPsubw,
    kIdPswapd,
    kIdPtest,
    kIdPtwrite,
    kIdPunpckhbw,
    kIdPunpckhdq,
    kIdPunpckhqdq,
    kIdPunpckhwd,
    kIdPunpcklbw,
    kIdPunpckldq,
    kIdPunpcklqdq,
    kIdPunpcklwd,
    kIdPush,
    kIdPusha,
    kIdPushad,
    kIdPushf,
    kIdPushfd,
    kIdPushfq,
    kIdPushw,
    kIdPvalidate,
    kIdPxor,
    kIdRcl,
    kIdRcpps,
    kIdRcpss,
    kIdRcr,
    kIdRdfsbase,
    kIdRdgsbase,
    kIdRdmsr,
    kIdRdpid,
    kIdRdpkru,
    kIdRdpmc,
    kIdRdpru,
    kIdRdrand,
    kIdRdseed,
    kIdRdsspd,
    kIdRdsspq,
    kIdRdtsc,
    kIdRdtscp,
    kIdRet,
    kIdRetf,
    kIdRmpadjust,
    kIdRmpupdate,
    kIdRol,
    kIdRor,
    kIdRorx,
    kIdRoundpd,
    kIdRoundps,
    kIdRoundsd,
    kIdRoundss,
    kIdRsm,
    kIdRsqrtps,
    kIdRsqrtss,
    kIdRstorssp,
    kIdSahf,
    kIdSar,
    kIdSarx,
    kIdSaveprevssp,
    kIdSbb,
    kIdScas,
    kIdSeamcall,
    kIdSeamops,
    kIdSeamret,
    kIdSenduipi,
    kIdSerialize,
    kIdSetb,
    kIdSetbe,
    kIdSetl,
    kIdSetle,
    kIdSetnb,
    kIdSetnbe,
    kIdSetnl,
    kIdSetnle,
    kIdSetno,
    kIdSetnp,
    kIdSetns,
    kIdSetnz,
    kIdSeto,
    kIdSetp,
    kIdSets,
    kIdSetssbsy,
    kIdSetz,
    kIdSfence,
    kIdSgdt,
    kIdSha1msg1,
    kIdSha1msg2,
    kIdSha1nexte,
    kIdSha1rnds4,
    kIdSha256msg1,
    kIdSha256msg2,
    kIdSha256rnds2,
    kIdShl,
    kIdShld,
    kIdShlx,
    kIdShr,
    kIdShrd,
    kIdShrx,
    kIdShufpd,
    kIdShufps,
    kIdSidt,
    kIdSkinit,
    kIdSldt,
    kIdSlwpcb,
    kIdSmsw,
    kIdSqrtpd,
    kIdSqrtps,
    kIdSqrtsd,
    kIdSqrtss,
    kIdStac,
    kIdStc,
    kIdStd,
    kIdStgi,
    kIdSti,
    kIdStmxcsr,
    kIdStos,
    kIdStr,
    kIdSttilecfg,
    kIdStui,
    kIdSub,
    kIdSubpd,
    kIdSubps,
    kIdSubsd,
    kIdSubss,
    kIdSwapgs,
    kIdSyscall,
    kIdSysenter,
    kIdSysexit,
    kIdSysexitq,
    kIdSysret,
    kIdSysretq,
    kIdT1mskc,
    kIdTcmmimfp16ps,
    kIdTcmmrlfp16ps,
    kIdTdcall,
    kIdTdpbf16ps,
    kIdTdpbssd,
    kIdTdpbsud,
    kIdTdpbusd,
    kIdTdpbuud,
    kIdTdpfp16ps,
    kIdTest,
    kIdTestui,
    kIdTileloadd,
    kIdTileloaddt1,
    kIdTilerelease,
    kIdTilestored,
    kIdTilezero,
    kIdTlbsync,
    kIdTpause,
    kIdTzcnt,
    kIdTzmsk,
    kIdUcomisd,
    kIdUcomiss,
    kIdUd0,
    kIdUd1,
    kIdUd2,
    kIdUiret,
    kIdUmonitor,
    kIdUmwait,
    kIdUnpckhpd,
    kIdUnpckhps,
    kIdUnpcklpd,
    kIdUnpcklps,
    kIdVaddpd,
    kIdVaddph,
    kIdVaddps,
    kIdVaddsd,
    kIdVaddsh,
    kIdVaddss,
    kIdVaddsubpd,
    kIdVaddsubps,
    kIdVaesdec,
    kIdVaesdeclast,
    kIdVaesenc,
    kIdVaesenclast,
    kIdVaesimc,
    kIdVaeskeygenassist,
    kIdValignd,
    kIdValignq,
    kIdVandnpd,
    kIdVandnps,
    kIdVandpd,
    kIdVandps,
    kIdVbcstnebf162ps,
    kIdVbcstnesh2ps,
    kIdVblendmpd,
    kIdVblendmps,
    kIdVblendpd,
    kIdVblendps,
    kIdVblendvpd,
    kIdVblendvps,
    kIdVbroadcastf128,
    kIdVbroadcastf32x2,
    kIdVbroadcastf32x4,
    kIdVbroadcastf32x8,
    kIdVbroadcastf64x2,
    kIdVbroadcastf64x4,
    kIdVbroadcasti128,
    kIdVbroadcasti32x2,
    kIdVbroadcasti32x4,
    kIdVbroadcasti32x8,
    kIdVbroadcasti64x2,
    kIdVbroadcasti64x4,
    kIdVbroadcastsd,
    kIdVbroadcastss,
    kIdVcmppd,
    kIdVcmpph,
    kIdVcmpps,
    kIdVcmpsd,
    kIdVcmpsh,
    kIdVcmpss,
    kIdVcomisd,
    kIdVcomish,
    kIdVcomiss,
    kIdVcompresspd,
    kIdVcompressps,
    kIdVcvtdq2pd,
    kIdVcvtdq2ph,
    kIdVcvtdq2ps,
    kIdVcvtne2ps2bf16,
    kIdVcvtneebf162ps,
    kIdVcvtneeph2ps,
    kIdVcvtneobf162ps,
    kIdVcvtneoph2ps,
    kIdVcvtneps2bf16,
    kIdVcvtpd2dq,
    kIdVcvtpd2ph,
    kIdVcvtpd2ps,
    kIdVcvtpd2qq,
    kIdVcvtpd2udq,
    kIdVcvtpd2uqq,
    kIdVcvtph2dq,
    kIdVcvtph2pd,
    kIdVcvtph2ps,
    kIdVcvtph2psx,
    kIdVcvtph2qq,
    kIdVcvtph2udq,
    kIdVcvtph2uqq,
    kIdVcvtph2uw,
    kIdVcvtph2w,
    kIdVcvtps2dq,
    kIdVcvtps2pd,
    kIdVcvtps2ph,
    kIdVcvtps2phx,
    kIdVcvtps2qq,
    kIdVcvtps2udq,
    kIdVcvtps2uqq,
    kIdVcvtqq2pd,
    kIdVcvtqq2ph,
    kIdVcvtqq2ps,
    kIdVcvtsd2sh,
    kIdVcvtsd2si,
    kIdVcvtsd2ss,
    kIdVcvtsd2usi,
    kIdVcvtsh2sd,
    kIdVcvtsh2si,
    kIdVcvtsh2ss,
    kIdVcvtsh2usi,
    kIdVcvtsi2sd,
    kIdVcvtsi2sh,
    kIdVcvtsi2ss,
    kIdVcvtss2sd,
    kIdVcvtss2sh,
    kIdVcvtss2si,
    kIdVcvtss2usi,
    kIdVcvttpd2dq,
    kIdVcvttpd2qq,
    kIdVcvttpd2udq,
    kIdVcvttpd2uqq,
    kIdVcvttph2dq,
    kIdVcvttph2qq,
    kIdVcvttph2udq,
    kIdVcvttph2uqq,
    kIdVcvttph2uw,
    kIdVcvttph2w,
    kIdVcvttps2dq,
    kIdVcvttps2qq,
    kIdVcvttps2udq,
    kIdVcvttps2uqq,
    kIdVcvttsd2si,
    kIdVcvttsd2usi,
    kIdVcvttsh2si,
    kIdVcvttsh2usi,
    kIdVcvttss2si,
    kIdVcvttss2usi,
    kIdVcvtudq2pd,
    kIdVcvtudq2ph,
    kIdVcvtudq2ps,
    kIdVcvtuqq2pd,
    kIdVcvtuqq2ph,
    kIdVcvtuqq2ps,
    kIdVcvtusi2sd,
    kIdVcvtusi2sh,
    kIdVcvtusi2ss,
    kIdVcvtuw2ph,
    kIdVcvtw2ph,
    kIdVdbpsadbw,
    kIdVdivpd,
    kIdVdivph,
    kIdVdivps,
    kIdVdivsd,
    kIdVdivsh,
    kIdVdivss,
    kIdVdpbf16ps,
    kIdVdppd,
    kIdVdpps,
    kIdVerr,
    kIdVerw,
    kIdVexpandpd,
    kIdVexpandps,
    kIdVextractf128,
    kIdVextractf32x4,
    kIdVextractf32x8,
    kIdVextractf64x2,
    kIdVextractf64x4,
    kIdVextracti128,
    kIdVextracti32x4,
    kIdVextracti32x8,
    kIdVextracti64x2,
    kIdVextracti64x4,
    kIdVextractps,
    kIdVfcmaddcph,
    kIdVfcmaddcsh,
    kIdVfcmulcph,
    kIdVfcmulcsh,
    kIdVfixupimmpd,
    kIdVfixupimmps,
    kIdVfixupimmsd,
    kIdVfixupimmss,
    kIdVfmadd132pd,
    kIdVfmadd132ph,
    kIdVfmadd132ps,
    kIdVfmadd132sd,
    kIdVfmadd132sh,
    kIdVfmadd132ss,
    kIdVfmadd213pd,
    kIdVfmadd213ph,
    kIdVfmadd213ps,
    kIdVfmadd213sd,
    kIdVfmadd213sh,
    kIdVfmadd213ss,
    kIdVfmadd231pd,
    kIdVfmadd231ph,
    kIdVfmadd231ps,
    kIdVfmadd231sd,
    kIdVfmadd231sh,
    kIdVfmadd231ss,
    kIdVfmaddcph,
    kIdVfmaddcsh,
    kIdVfmaddpd,
    kIdVfmaddps,
    kIdVfmaddsd,
    kIdVfmaddss,
    kIdVfmaddsub132pd,
    kIdVfmaddsub132ph,
    kIdVfmaddsub132ps,
    kIdVfmaddsub213pd,
    kIdVfmaddsub213ph,
    kIdVfmaddsub213ps,
    kIdVfmaddsub231pd,
    kIdVfmaddsub231ph,
    kIdVfmaddsub231ps,
    kIdVfmaddsubpd,
    kIdVfmaddsubps,
    kIdVfmsub132pd,
    kIdVfmsub132ph,
    kIdVfmsub132ps,
    kIdVfmsub132sd,
    kIdVfmsub132sh,
    kIdVfmsub132ss,
    kIdVfmsub213pd,
    kIdVfmsub213ph,
    kIdVfmsub213ps,
    kIdVfmsub213sd,
    kIdVfmsub213sh,
    kIdVfmsub213ss,
    kIdVfmsub231pd,
    kIdVfmsub231ph,
    kIdVfmsub231ps,
    kIdVfmsub231sd,
    kIdVfmsub231sh,
    kIdVfmsub231ss,
    kIdVfmsubadd132pd,
    kIdVfmsubadd132ph,
    kIdVfmsubadd132ps,
    kIdVfmsubadd213pd,
    kIdVfmsubadd213ph,
    kIdVfmsubadd213ps,
    kIdVfmsubadd231pd,
    kIdVfmsubadd231ph,
    kIdVfmsubadd231ps,
    kIdVfmsubaddpd,
    kIdVfmsubaddps,
    kIdVfmsubpd,
    kIdVfmsubps,
    kIdVfmsubsd,
    kIdVfmsubss,
    kIdVfmulcph,
    kIdVfmulcsh,
    kIdVfnmadd132pd,
    kIdVfnmadd132ph,
    kIdVfnmadd132ps,
    kIdVfnmadd132sd,
    kIdVfnmadd132sh,
    kIdVfnmadd132ss,
    kIdVfnmadd213pd,
    kIdVfnmadd213ph,
    kIdVfnmadd213ps,
    kIdVfnmadd213sd,
    kIdVfnmadd213sh,
    kIdVfnmadd213ss,
    kIdVfnmadd231pd,
    kIdVfnmadd231ph,
    kIdVfnmadd231ps,
    kIdVfnmadd231sd,
    kIdVfnmadd231sh,
    kIdVfnmadd231ss,
    kIdVfnmaddpd,
    kIdVfnmaddps,
    kIdVfnmaddsd,
    kIdVfnmaddss,
    kIdVfnmsub132pd,
    kIdVfnmsub132ph,
    kIdVfnmsub132ps,
    kIdVfnmsub132sd,
    kIdVfnmsub132sh,
    kIdVfnmsub132ss,
    kIdVfnmsub213pd,
    kIdVfnmsub213ph,
    kIdVfnmsub213ps,
    kIdVfnmsub213sd,
    kIdVfnmsub213sh,
    kIdVfnmsub213ss,
    kIdVfnmsub231pd,
    kIdVfnmsub231ph,
    kIdVfnmsub231ps,
    kIdVfnmsub231sd,
    kIdVfnmsub231sh,
    kIdVfnmsub231ss,
    kIdVfnmsubpd,
    kIdVfnmsubps,
    kIdVfnmsubsd,
    kIdVfnmsubss,
    kIdVfpclasspd,
    kIdVfpclassph,
    kIdVfpclassps,
    kIdVfpclasssd,
    kIdVfpclasssh,
    kIdVfpclassss,
    kIdVfrczpd,
    kIdVfrczps,
    kIdVfrczsd,
    kIdVfrczss,
    kIdVgatherdpd,
    kIdVgatherdps,
    kIdVgatherqpd,
    kIdVgatherqps,
    kIdVgetexppd,
    kIdVgetexpph,
    kIdVgetexpps,
    kIdVgetexpsd,
    kIdVgetexpsh,
    kIdVgetexpss,
    kIdVgetmantpd,
    kIdVgetmantph,
    kIdVgetmantps,
    kIdVgetmantsd,
    kIdVgetmantsh,
    kIdVgetmantss,
    kIdVgf2p8affineinvqb,
    kIdVgf2p8affineqb,
    kIdVgf2p8mulb,
    kIdVhaddpd,
    kIdVhaddps,
    kIdVhsubpd,
    kIdVhsubps,
    kIdVinsertf128,
    kIdVinsertf32x4,
    kIdVinsertf32x8,
    kIdVinsertf64x2,
    kIdVinsertf64x4,
    kIdVinserti128,
    kIdVinserti32x4,
    kIdVinserti32x8,
    kIdVinserti64x2,
    kIdVinserti64x4,
    kIdVinsertps,
    kIdVlddqu,
    kIdVldmxcsr,
    kIdVmaskmovdqu,
    kIdVmaskmovpd,
    kIdVmaskmovps,
    kIdVmaxpd,
    kIdVmaxph,
    kIdVmaxps,
    kIdVmaxsd,
    kIdVmaxsh,
    kIdVmaxss,
    kIdVmcall,
    kIdVmclear,
    kIdVmfunc,
    kIdVmgexit,
    kIdVminpd,
    kIdVminph,
    kIdVminps,
    kIdVminsd,
    kIdVminsh,
    kIdVminss,
    kIdVmlaunch,
    kIdVmload,
    kIdVmmcall,
    kIdVmovapd,
    kIdVmovaps,
    kIdVmovd,
    kIdVmovddup,
    kIdVmovdqa,
    kIdVmovdqa32,
    kIdVmovdqa64,
    kIdVmovdqu,
    kIdVmovdqu16,
    kIdVmovdqu32,
    kIdVmovdqu64,
    kIdVmovdqu8,
    kIdVmovhlps,
    kIdVmovhpd,
    kIdVmovhps,
    kIdVmovlhps,
    kIdVmovlpd,
    kIdVmovlps,
    kIdVmovmskpd,
    kIdVmovmskps,
    kIdVmovntdq,
    kIdVmovntdqa,
    kIdVmovntpd,
    kIdVmovntps,
    kIdVmovq,
    kIdVmovsd,
    kIdVmovsh,
    kIdVmovshdup,
    kIdVmovsldup,
    kIdVmovss,
    kIdVmovupd,
    kIdVmovups,
    kIdVmovw,
    kIdVmpsadbw,
    kIdVmptrld,
    kIdVmptrst,
    kIdVmread,
    kIdVmresume,
    kIdVmrun,
    kIdVmsave,
    kIdVmulpd,
    kIdVmulph,
    kIdVmulps,
    kIdVmulsd,
    kIdVmulsh,
    kIdVmulss,
    kIdVmwrite,
    kIdVmxoff,
    kIdVmxon,
    kIdVorpd,
    kIdVorps,
    kIdVp2intersectd,
    kIdVp2intersectq,
    kIdVpabsb,
    kIdVpabsd,
    kIdVpabsq,
    kIdVpabsw,
    kIdVpackssdw,
    kIdVpacksswb,
    kIdVpackusdw,
    kIdVpackuswb,
    kIdVpaddb,
    kIdVpaddd,
    kIdVpaddq,
    kIdVpaddsb,
    kIdVpaddsw,
    kIdVpaddusb,
    kIdVpaddusw,
    kIdVpaddw,
    kIdVpalignr,
    kIdVpand,
    kIdVpandd,
    kIdVpandn,
    kIdVpandnd,
    kIdVpandnq,
    kIdVpandq,
    kIdVpavgb,
    kIdVpavgw,
    kIdVpblendd,
    kIdVpblendmb,
    kIdVpblendmd,
    kIdVpblendmq,
    kIdVpblendmw,
    kIdVpblendvb,
    kIdVpblendw,
    kIdVpbroadcastb,
    kIdVpbroadcastd,
    kIdVpbroadcastmb2q,
    kIdVpbroadcastmw2d,
    kIdVpbroadcastq,
    kIdVpbroadcastw,
    kIdVpclmulqdq,
    kIdVpcmov,
    kIdVpcmpb,
    kIdVpcmpd,
    kIdVpcmpeqb,
    kIdVpcmpeqd,
    kIdVpcmpeqq,
    kIdVpcmpeqw,
    kIdVpcmpestri,
    kIdVpcmpestrm,
    kIdVpcmpgtb,
    kIdVpcmpgtd,
    kIdVpcmpgtq,
    kIdVpcmpgtw,
    kIdVpcmpistri,
    kIdVpcmpistrm,
    kIdVpcmpq,
    kIdVpcmpub,
    kIdVpcmpud,
    kIdVpcmpuq,
    kIdVpcmpuw,
    kIdVpcmpw,
    kIdVpcomb,
    kIdVpcomd,
    kIdVpcompressb,
    kIdVpcompressd,
    kIdVpcompressq,
    kIdVpcompressw,
    kIdVpcomq,
    kIdVpcomub,
    kIdVpcomud,
    kIdVpcomuq,
    kIdVpcomuw,
    kIdVpcomw,
    kIdVpconflictd,
    kIdVpconflictq,
    kIdVpdpbssd,
    kIdVpdpbssds,
    kIdVpdpbsud,
    kIdVpdpbsuds,
    kIdVpdpbusd,
    kIdVpdpbusds,
    kIdVpdpbuud,
    kIdVpdpbuuds,
    kIdVpdpwssd,
    kIdVpdpwssds,
    kIdVpdpwsud,
    kIdVpdpwsuds,
    kIdVpdpwusd,
    kIdVpdpwusds,
    kIdVpdpwuud,
    kIdVpdpwuuds,
    kIdVperm2f128,
    kIdVperm2i128,
    kIdVpermb,
    kIdVpermd,
    kIdVpermi2b,
    kIdVpermi2d,
    kIdVpermi2pd,
    kIdVpermi2ps,
    kIdVpermi2q,
    kIdVpermi2w,
    kIdVpermil2pd,
    kIdVpermil2ps,
    kIdVpermilpd,
    kIdVpermilps,
    kIdVpermpd,
    kIdVpermps,
    kIdVpermq,
    kIdVpermt2b,
    kIdVpermt2d,
    kIdVpermt2pd,
    kIdVpermt2ps,
    kIdVpermt2q,
    kIdVpermt2w,
    kIdVpermw,
    kIdVpexpandb,
    kIdVpexpandd,
    kIdVpexpandq,
    kIdVpexpandw,
    kIdVpextrb,
    kIdVpextrd,
    kIdVpextrq,
    kIdVpextrw,
    kIdVpgatherdd,
    kIdVpgatherdq,
    kIdVpgatherqd,
    kIdVpgatherqq,
    kIdVphaddbd,
    kIdVphaddbq,
    kIdVphaddbw,
    kIdVphaddd,
    kIdVphadddq,
    kIdVphaddsw,
    kIdVphaddubd,
    kIdVphaddubq,
    kIdVphaddubw,
    kIdVphaddudq,
    kIdVphadduwd,
    kIdVphadduwq,
    kIdVphaddw,
    kIdVphaddwd,
    kIdVphaddwq,
    kIdVphminposuw,
    kIdVphsubbw,
    kIdVphsubd,
    kIdVphsubdq,
    kIdVphsubsw,
    kIdVphsubw,
    kIdVphsubwd,
    kIdVpinsrb,
    kIdVpinsrd,
    kIdVpinsrq,
    kIdVpinsrw,
    kIdVplzcntd,
    kIdVplzcntq,
    kIdVpmacsdd,
    kIdVpmacsdqh,
    kIdVpmacsdql,
    kIdVpmacssdd,
    kIdVpmacssdqh,
    kIdVpmacssdql,
    kIdVpmacsswd,
    kIdVpmacssww,
    kIdVpmacswd,
    kIdVpmacsww,
    kIdVpmadcsswd,
    kIdVpmadcswd,
    kIdVpmadd52huq,
    kIdVpmadd52luq,
    kIdVpmaddubsw,
    kIdVpmaddwd,
    kIdVpmaskmovd,
    kIdVpmaskmovq,
    kIdVpmaxsb,
    kIdVpmaxsd,
    kIdVpmaxsq,
    kIdVpmaxsw,
    kIdVpmaxub,
    kIdVpmaxud,
    kIdVpmaxuq,
    kIdVpmaxuw,
    kIdVpminsb,
    kIdVpminsd,
    kIdVpminsq,
    kIdVpminsw,
    kIdVpminub,
    kIdVpminud,
    kIdVpminuq,
    kIdVpminuw,
    kIdVpmovb2m,
    kIdVpmovd2m,
    kIdVpmovdb,
    kIdVpmovdw,
    kIdVpmovm2b,
    kIdVpmovm2d,
    kIdVpmovm2q,
    kIdVpmovm2w,
    kIdVpmovmskb,
    kIdVpmovq2m,
    kIdVpmovqb,
    kIdVpmovqd,
    kIdVpmovqw,
    kIdVpmovsdb,
    kIdVpmovsdw,
    kIdVpmovsqb,
    kIdVpmovsqd,
    kIdVpmovsqw,
    kIdVpmovswb,
    kIdVpmovsxbd,
    kIdVpmovsxbq,
    kIdVpmovsxbw,
    kIdVpmovsxdq,
    kIdVpmovsxwd,
    kIdVpmovsxwq,
    kIdVpmovusdb,
    kIdVpmovusdw,
    kIdVpmovusqb,
    kIdVpmovusqd,
    kIdVpmovusqw,
    kIdVpmovuswb,
    kIdVpmovw2m,
    kIdVpmovwb,
    kIdVpmovzxbd,
    kIdVpmovzxbq,
    kIdVpmovzxbw,
    kIdVpmovzxdq,
    kIdVpmovzxwd,
    kIdVpmovzxwq,
    kIdVpmuldq,
    kIdVpmulhrsw,
    kIdVpmulhuw,
    kIdVpmulhw,
    kIdVpmulld,
    kIdVpmullq,
    kIdVpmullw,
    kIdVpmultishiftqb,
    kIdVpmuludq,
    kIdVpopcntb,
    kIdVpopcntd,
    kIdVpopcntq,
    kIdVpopcntw,
    kIdVpor,
    kIdVpord,
    kIdVporq,
    kIdVpperm,
    kIdVprold,
    kIdVprolq,
    kIdVprolvd,
    kIdVprolvq,
    kIdVprord,
    kIdVprorq,
    kIdVprorvd,
    kIdVprorvq,
    kIdVprotb,
    kIdVprotd,
    kIdVprotq,
    kIdVprotw,
    kIdVpsadbw,
    kIdVpscatterdd,
    kIdVpscatterdq,
    kIdVpscatterqd,
    kIdVpscatterqq,
    kIdVpshab,
    kIdVpshad,
    kIdVpshaq,
    kIdVpshaw,
    kIdVpshlb,
    kIdVpshld,
    kIdVpshldd,
    kIdVpshldq,
    kIdVpshldvd,
    kIdVpshldvq,
    kIdVpshldvw,
    kIdVpshldw,
    kIdVpshlq,
    kIdVpshlw,
    kIdVpshrdd,
    kIdVpshrdq,
    kIdVpshrdvd,
    kIdVpshrdvq,
    kIdVpshrdvw,
    kIdVpshrdw,
    kIdVpshufb,
    kIdVpshufbitqmb,
    kIdVpshufd,
    kIdVpshufhw,
    kIdVpshuflw,
    kIdVpsignb,
    kIdVpsignd,
    kIdVpsignw,
    kIdVpslld,
    kIdVpslldq,
    kIdVpsllq,
    kIdVpsllvd,
    kIdVpsllvq,
    kIdVpsllvw,
    kIdVpsllw,
    kIdVpsrad,
    kIdVpsraq,
    kIdVpsravd,
    kIdVpsravq,
    kIdVpsravw,
    kIdVpsraw,
    kIdVpsrld,
    kIdVpsrldq,
    kIdVpsrlq,
    kIdVpsrlvd,
    kIdVpsrlvq,
    kIdVpsrlvw,
    kIdVpsrlw,
    kIdVpsubb,
    kIdVpsubd,
    kIdVpsubq,
    kIdVpsubsb,
    kIdVpsubsw,
    kIdVpsubusb,
    kIdVpsubusw,
    kIdVpsubw,
    kIdVpternlogd,
    kIdVpternlogq,
    kIdVptest,
    kIdVptestmb,
    kIdVptestmd,
    kIdVptestmq,
    kIdVptestmw,
    kIdVptestnmb,
    kIdVptestnmd,
    kIdVptestnmq,
    kIdVptestnmw,
    kIdVpunpckhbw,
    kIdVpunpckhdq,
    kIdVpunpckhqdq,
    kIdVpunpckhwd,
    kIdVpunpcklbw,
    kIdVpunpckldq,
    kIdVpunpcklqdq,
    kIdVpunpcklwd,
    kIdVpxor,
    kIdVpxord,
    kIdVpxorq,
    kIdVrangepd,
    kIdVrangeps,
    kIdVrangesd,
    kIdVrangess,
    kIdVrcp14pd,
    kIdVrcp14ps,
    kIdVrcp14sd,
    kIdVrcp14ss,
    kIdVrcpph,
    kIdVrcpps,
    kIdVrcpsh,
    kIdVrcpss,
    kIdVreducepd,
    kIdVreduceph,
    kIdVreduceps,
    kIdVreducesd,
    kIdVreducesh,
    kIdVreducess,
    kIdVrndscalepd,
    kIdVrndscaleph,
    kIdVrndscaleps,
    kIdVrndscalesd,
    kIdVrndscalesh,
    kIdVrndscaless,
    kIdVroundpd,
    kIdVroundps,
    kIdVroundsd,
    kIdVroundss,
    kIdVrsqrt14pd,
    kIdVrsqrt14ps,
    kIdVrsqrt14sd,
    kIdVrsqrt14ss,
    kIdVrsqrtph,
    kIdVrsqrtps,
    kIdVrsqrtsh,
    kIdVrsqrtss,
    kIdVscalefpd,
    kIdVscalefph,
    kIdVscalefps,
    kIdVscalefsd,
    kIdVscalefsh,
    kIdVscalefss,
    kIdVscatterdpd,
    kIdVscatterdps,
    kIdVscatterqpd,
    kIdVscatterqps,
    kIdVsha512msg1,
    kIdVsha512msg2,
    kIdVsha512rnds2,
    kIdVshuff32x4,
    kIdVshuff64x2,
    kIdVshufi32x4,
    kIdVshufi64x2,
    kIdVshufpd,
    kIdVshufps,
    kIdVsm3msg1,
    kIdVsm3msg2,
    kIdVsm3rnds2,
    kIdVsm4key4,
    kIdVsm4rnds4,
    kIdVsqrtpd,
    kIdVsqrtph,
    kIdVsqrtps,
    kIdVsqrtsd,
    kIdVsqrtsh,
    kIdVsqrtss,
    kIdVstmxcsr,
    kIdVsubpd,
    kIdVsubph,
    kIdVsubps,
    kIdVsubsd,
    kIdVsubsh,
    kIdVsubss,
    kIdVtestpd,
    kIdVtestps,
    kIdVucomisd,
    kIdVucomish,
    kIdVucomiss,
    kIdVunpckhpd,
    kIdVunpckhps,
    kIdVunpcklpd,
    kIdVunpcklps,
    kIdVxorpd,
    kIdVxorps,
    kIdVzeroall,
    kIdVzeroupper,
    kIdWbinvd,
    kIdWbnoinvd,
    kIdWrfsbase,
    kIdWrgsbase,
    kIdWrmsr,
    kIdWrssd,
    kIdWrssq,
    kIdWrussd,
    kIdWrussq,
    kIdXabort,
    kIdXadd,
    kIdXbegin,
    kIdXchg,
    kIdXend,
    kIdXgetbv,
    kIdXlatb,
    kIdXor,
    kIdXorpd,
    kIdXorps,
    kIdXresldtrk,
    kIdXrstor,
    kIdXrstor64,
    kIdXrstors,
    kIdXrstors64,
    kIdXsave,
    kIdXsave64,
    kIdXsavec,
    kIdXsavec64,
    kIdXsaveopt,
    kIdXsaveopt64,
    kIdXsaves,
    kIdXsaves64,
    kIdXsetbv,
    kIdXsusldtrk,
    kIdXtest,
    _kIdCount,
    kIdCmovnae = kIdCmovb,
    kIdCmovc = kIdCmovb,
    kIdCmovna = kIdCmovbe,
    kIdCmovnge = kIdCmovl,
    kIdCmovng = kIdCmovle,
    kIdCmovae = kIdCmovnb,
    kIdCmovnc = kIdCmovnb,
    kIdCmova = kIdCmovnbe,
    kIdCmovge = kIdCmovnl,
    kIdCmovg = kIdCmovnle,
    kIdCmovpo = kIdCmovnp,
    kIdCmovne = kIdCmovnz,
    kIdCmovpe = kIdCmovp,
    kIdCmove = kIdCmovz,
    kIdWait = kIdFwait,
    kIdJnae = kIdJb,
    kIdJc = kIdJb,
    kIdJna = kIdJbe,
    kIdJnge = kIdJl,
    kIdJng = kIdJle,
    kIdJae = kIdJnb,
    kIdJnc = kIdJnb,
    kIdJa = kIdJnbe,
    kIdJge = kIdJnl,
    kIdJg = kIdJnle,
    kIdJpo = kIdJnp,
    kIdJne = kIdJnz,
    kIdJpe = kIdJp,
    kIdJe = kIdJz,
    kIdSetnae = kIdSetb,
    kIdSetc = kIdSetb,
    kIdSetna = kIdSetbe,
    kIdSetnge = kIdSetl,
    kIdSetng = kIdSetle,
    kIdSetae = kIdSetnb,
    kIdSetnc = kIdSetnb,
    kIdSeta = kIdSetnbe,
    kIdSetge = kIdSetnl,
    kIdSetg = kIdSetnle,
    kIdSetpo = kIdSetnp,
    kIdSetne = kIdSetnz,
    kIdSetpe = kIdSetp,
    kIdSete = kIdSetz,
    kIdSal = kIdShl
  };
  static ASMJIT_INLINE_CONSTEXPR bool is_defined_id(InstId inst_id) noexcept { return inst_id < _kIdCount; }
  #define ASMJIT_INST_FROM_COND(ID) \
    ID##o, ID##no, ID##b , ID##nb , \
    ID##z, ID##nz, ID##be, ID##nbe, \
    ID##s, ID##ns, ID##p , ID##np , \
    ID##l, ID##nl, ID##le, ID##nle
    static constexpr uint16_t _jcc_from_cond_table[] = { ASMJIT_INST_FROM_COND(Inst::kIdJ) };
    static constexpr uint16_t _setcc_from_cond_table[] = { ASMJIT_INST_FROM_COND(Inst::kIdSet) };
    static constexpr uint16_t _cmovcc_from_cond_table[] = { ASMJIT_INST_FROM_COND(Inst::kIdCmov) };
  #undef ASMJIT_INST_FROM_COND
  static ASMJIT_INLINE_CONSTEXPR InstId jcc_from_cond(CondCode cond) noexcept { return _jcc_from_cond_table[uint8_t(cond)]; }
  static ASMJIT_INLINE_CONSTEXPR InstId setcc_from_cond(CondCode cond) noexcept { return _setcc_from_cond_table[uint8_t(cond)]; }
  static ASMJIT_INLINE_CONSTEXPR InstId cmovcc_from_cond(CondCode cond) noexcept { return _cmovcc_from_cond_table[uint8_t(cond)]; }
}
enum class FpuStatusWord : uint16_t {
  kNone          = 0x0000u,
  kInvalid       = 0x0001u,
  kDenormalized  = 0x0002u,
  kDivByZero     = 0x0004u,
  kOverflow      = 0x0008u,
  kUnderflow     = 0x0010u,
  kPrecision     = 0x0020u,
  kStackFault    = 0x0040u,
  kInterrupt     = 0x0080u,
  kC0            = 0x0100u,
  kC1            = 0x0200u,
  kC2            = 0x0400u,
  kTopMask       = 0x3800u,
  kC3            = 0x4000u,
  kBusy          = 0x8000u
};
ASMJIT_DEFINE_ENUM_FLAGS(FpuStatusWord)
enum class FpuControlWord : uint16_t {
  kNone          = 0x0000u,
  kEM_Mask       = 0x003Fu,
  kEM_Invalid    = 0x0001u,
  kEM_Denormal   = 0x0002u,
  kEM_DivByZero  = 0x0004u,
  kEM_Overflow   = 0x0008u,
  kEM_Underflow  = 0x0010u,
  kEM_Inexact    = 0x0020u,
  kPC_Mask       = 0x0300u,
  kPC_Float      = 0x0000u,
  kPC_Reserved   = 0x0100u,
  kPC_Double     = 0x0200u,
  kPC_Extended   = 0x0300u,
  kRC_Mask       = 0x0C00u,
  kRC_Nearest    = 0x0000u,
  kRC_Down       = 0x0400u,
  kRC_Up         = 0x0800u,
  kRC_Truncate   = 0x0C00u,
  kIC_Mask       = 0x1000u,
  kIC_Projective = 0x0000u,
  kIC_Affine     = 0x1000u
};
ASMJIT_DEFINE_ENUM_FLAGS(FpuControlWord)
enum class CmpImm : uint8_t {
  kEQ            = 0x00u,
  kLT            = 0x01u,
  kLE            = 0x02u,
  kUNORD         = 0x03u,
  kNEQ           = 0x04u,
  kNLT           = 0x05u,
  kNLE           = 0x06u,
  kORD           = 0x07u
};
enum class PCmpStrImm : uint8_t {
  kUB            = 0x00u << 0,
  kUW            = 0x01u << 0,
  kSB            = 0x02u << 0,
  kSW            = 0x03u << 0,
  kEqualAny      = 0x00u << 2,
  kRanges        = 0x01u << 2,
  kEqualEach     = 0x02u << 2,
  kEqualOrdered  = 0x03u << 2,
  kPosPolarity   = 0x00u << 4,
  kNegPolarity   = 0x01u << 4,
  kPosMasked     = 0x02u << 4,
  kNegMasked     = 0x03u << 4,
  kOutputLSI     = 0x00u << 6,
  kOutputMSI     = 0x01u << 6,
  kBitMask       = 0x00u << 6,
  kIndexMask     = 0x01u << 6
};
ASMJIT_DEFINE_ENUM_FLAGS(PCmpStrImm)
enum class RoundImm : uint8_t {
  kNearest       = 0x00u,
  kDown          = 0x01u,
  kUp            = 0x02u,
  kTrunc         = 0x03u,
  kCurrent       = 0x04u,
  kSuppress      = 0x08u
};
ASMJIT_DEFINE_ENUM_FLAGS(RoundImm)
enum class VCmpImm : uint8_t {
  kEQ_OQ         = 0x00u,
  kLT_OS         = 0x01u,
  kLE_OS         = 0x02u,
  kUNORD_Q       = 0x03u,
  kNEQ_UQ        = 0x04u,
  kNLT_US        = 0x05u,
  kNLE_US        = 0x06u,
  kORD_Q         = 0x07u,
  kEQ_UQ         = 0x08u,
  kNGE_US        = 0x09u,
  kNGT_US        = 0x0Au,
  kFALSE_OQ      = 0x0Bu,
  kNEQ_OQ        = 0x0Cu,
  kGE_OS         = 0x0Du,
  kGT_OS         = 0x0Eu,
  kTRUE_UQ       = 0x0Fu,
  kEQ_OS         = 0x10u,
  kLT_OQ         = 0x11u,
  kLE_OQ         = 0x12u,
  kUNORD_S       = 0x13u,
  kNEQ_US        = 0x14u,
  kNLT_UQ        = 0x15u,
  kNLE_UQ        = 0x16u,
  kORD_S         = 0x17u,
  kEQ_US         = 0x18u,
  kNGE_UQ        = 0x19u,
  kNGT_UQ        = 0x1Au,
  kFALSE_OS      = 0x1Bu,
  kNEQ_OS        = 0x1Cu,
  kGE_OQ         = 0x1Du,
  kGT_OQ         = 0x1Eu,
  kTRUE_US       = 0x1Fu
};
enum class VFixupImm : uint8_t {
  kNone          = 0x00u,
  kZEOnZero      = 0x01u,
  kIEOnZero      = 0x02u,
  kZEOnOne       = 0x04u,
  kIEOnOne       = 0x08u,
  kIEOnSNaN      = 0x10u,
  kIEOnNInf      = 0x20u,
  kIEOnNegative  = 0x40u,
  kIEOnPInf      = 0x80u
};
ASMJIT_DEFINE_ENUM_FLAGS(VFixupImm)
enum class VFPClassImm : uint8_t {
  kNone          = 0x00u,
  kQNaN          = 0x01u,
  kPZero         = 0x02u,
  kNZero         = 0x04u,
  kPInf          = 0x08u,
  kNInf          = 0x10u,
  kDenormal      = 0x20u,
  kNegative      = 0x40u,
  kSNaN          = 0x80u
};
ASMJIT_DEFINE_ENUM_FLAGS(VFPClassImm)
enum class VGetMantImm : uint8_t {
  k1To2          = 0x00u,
  k1Div2To2      = 0x01u,
  k1Div2To1      = 0x02u,
  k3Div4To3Div2  = 0x03u,
  kSrcSign       = 0x00u,
  kNoSign        = 0x04u,
  kQNaNIfSign    = 0x08u
};
ASMJIT_DEFINE_ENUM_FLAGS(VGetMantImm)
enum class VPCmpImm : uint8_t {
  kEQ            = 0x00u,
  kLT            = 0x01u,
  kLE            = 0x02u,
  kFALSE         = 0x03u,
  kNE            = 0x04u,
  kGE            = 0x05u,
  kGT            = 0x06u,
  kTRUE          = 0x07u
};
enum class VPComImm : uint8_t {
  kLT            = 0x00u,
  kLE            = 0x01u,
  kGT            = 0x02u,
  kGE            = 0x03u,
  kEQ            = 0x04u,
  kNE            = 0x05u,
  kFALSE         = 0x06u,
  kTRUE          = 0x07u
};
enum class VRangeImm : uint8_t {
  kSelectMin     = 0x00u,
  kSelectMax     = 0x01u,
  kSelectAbsMin  = 0x02u,
  kSelectAbsMax  = 0x03u,
  kSignSrc1      = 0x00u,
  kSignSrc2      = 0x04u,
  kSign0         = 0x08u,
  kSign1         = 0x0Cu
};
ASMJIT_DEFINE_ENUM_FLAGS(VRangeImm)
enum class VReduceImm : uint8_t {
  kRoundEven     = 0x00u,
  kRoundDown     = 0x01u,
  kRoundUp       = 0x02u,
  kRoundTrunc    = 0x03u,
  kRoundCurrent  = 0x04u,
  kSuppress      = 0x08u,
  kFixedImmMask  = 0xF0u
};
ASMJIT_DEFINE_ENUM_FLAGS(VReduceImm)
static ASMJIT_INLINE_CONSTEXPR VReduceImm vreduce_imm(VReduceImm flags, uint32_t fixed_point_length) noexcept {
  return flags | VReduceImm(fixed_point_length << 4);
}
enum class TLogImm : uint8_t {
  k0             = 0x00u,
  k1             = 0xFFu,
  kA             = 0xF0u,
  kB             = 0xCCu,
  kC             = 0xAAu,
  kNotA          = kA ^ k1,
  kNotB          = kB ^ k1,
  kNotC          = kC ^ k1,
  kAB            = kA & kB,
  kAC            = kA & kC,
  kBC            = kB & kC,
  kNotAB         = kAB ^ k1,
  kNotAC         = kAC ^ k1,
  kNotBC         = kBC ^ k1,
  kABC           = kAB & kC,
  kNotABC        = kABC ^ k1
};
ASMJIT_DEFINE_ENUM_FLAGS(TLogImm)
static ASMJIT_INLINE_CONSTEXPR TLogImm tlog_from_bits(uint8_t b000, uint8_t b001, uint8_t b010, uint8_t b011, uint8_t b100, uint8_t b101, uint8_t b110, uint8_t b111) noexcept {
  return TLogImm(uint8_t(b000 << 0) |
                 uint8_t(b001 << 1) |
                 uint8_t(b010 << 2) |
                 uint8_t(b011 << 3) |
                 uint8_t(b100 << 4) |
                 uint8_t(b101 << 5) |
                 uint8_t(b110 << 6) |
                 uint8_t(b111 << 7));
}
static ASMJIT_INLINE_CONSTEXPR TLogImm tlog_if_else(TLogImm condition, TLogImm a, TLogImm b) noexcept { return (condition & a) | (~condition & b); }
static ASMJIT_INLINE_CONSTEXPR uint32_t shuffle_imm(uint32_t a, uint32_t b) noexcept {
  return (a << 1) | b;
}
static ASMJIT_INLINE_CONSTEXPR uint32_t shuffle_imm(uint32_t a, uint32_t b, uint32_t c, uint32_t d) noexcept {
  return (a << 6) | (b << 4) | (c << 2) | d;
}
ASMJIT_END_SUB_NAMESPACE
#endif